export const trybers = [
{
  id: '01',
  name: 'José Gomes',
  turma: '27-B',
  types: ['html'],
  alias: 'Loreal',
  animal: 'Cachorro',
  cidade: 'Recife-PE',
  frase: 'Xupa que é de Uva',
  pic: 'https://ca.slack-edge.com/TMDDFEPFU-U0405RK1T34-af9faf5ff4e2-512',
},
{
  id: '02',
  name: 'Gersinei Santos',
  turma: '27-B',
  types: ['html'],
  alias: 'GG Rotam',
  animal: 'Cachorro',
  cidade: 'Recife-PE',
  frase: 'Xupa que é de Uva',
  pic: 'https://ca.slack-edge.com/TMDDFEPFU-U03VD7NG1F0-001ff81bb6bf-512',
},
{
  id: '03',
  name: 'Pablo Landim',
  turma: '27-B',
  types: ['html'],
  alias: 'Pablito',
  animal: 'Cachorro',
  cidade: 'Campinas-SP',
  frase: 'Vai curíntia!',
  pic: 'https://ca.slack-edge.com/TMDDFEPFU-U03VD7VGUJ2-a55b511e9ca3-512',
},
{
  id: '04',
  name: 'Carlos Tonini',
  turma: '27-B',
  types: ['JS', 'PYTHON'],
  alias: 'Carlinhos',
  animal: 'Gato',
  cidade: 'Recife-PE',
  frase: 'Xupa que é de Uva',
  pic: 'https://ca.slack-edge.com/TMDDFEPFU-U03V58S6N1M-b6285a992b40-512',
},
{
  id: '05',
  name: 'Matheus Camargo',
  turma: '27-B',
  types: ['JS', 'DART', 'FLUTTER', 'REACT'],
  alias: 'Matheus',
  animal: 'Cachorro',
  cidade: 'Recife-PE',
  frase: 'Xupa que é de Uva',
  pic: 'https://ca.slack-edge.com/TMDDFEPFU-U0402SH6VA9-d4e49b68b2a7-512',
},
{
  id: '06',
  name: 'Alex Nunes',
  turma: '27-B',
  types: ['JS', 'PYTHON'],
  alias: 'alex === figma',
  animal: 'Gato',
  cidade: 'Recife-PE',
  frase: 'Xupa que é de Uva',
  pic: 'https://media.licdn.com/dms/image/D4D35AQEuPLe3Keksag/profile-framedphoto-shrink_200_200/0/1662480012893?e=1682305200&v=beta&t=G1_BD4r5cxDkY3RzxeIhrcaEbtiM5TcijztTOvoBxiw',
},
{
  id: '07',
  name: 'Walber Vaz da Silva',
  turma: '27-B',
  types: ['JS', 'PYTHON', 'JAVA', 'REACT', 'TYPESCRIPT'],
  alias: 'w2k',
  animal: 'Cachorro',
  cidade: 'Recife-PE',
  frase: 'Xupa que é de Uva',
  pic: 'https://ca.slack-edge.com/TMDDFEPFU-U0405N9NUHH-aa36978f333c-512',
},
{
  id: '08',
  name: 'Daniel Cintori',
  turma: '27-A',
  types: ['JS', 'PYTHON', 'JAVA', 'C', 'C++'],
  alias: 'DaniBoy',
  animal: 'Cachorro',
  cidade: 'Recife-PE',
  frase: 'Xupa que é de Uva',
  pic: 'https://ca.slack-edge.com/TMDDFEPFU-U040JEBMYAV-e13db50858dd-512',

},
{
  id: '09',
  name: 'Rafaela Granato',
  turma: '27-B',
  types: ['JS'],
  alias: 'Rafa',
  animal: 'Gato',
  cidade: 'Belo Horizonte-MG',
  frase: 'A vingança nunca é plena, mata a alma e a envenena',
  pic: 'https://ca.slack-edge.com/TMDDFEPFU-U040JEJKZRP-15670d5bdf63-512',
},
{
  id: '10',
  name: 'Artur',
  turma: '27-A',
  types: ['JS', 'JAVA', 'SQL', 'TYPESCRIPT', 'NODE'],
  alias: 'rutra',
  animal: 'Cachorro',
  cidade: 'Belo Horizonte -MG',
  frase: 'Além de não ser fácil, ainda é difícil', 
  pic: 'https://ca.slack-edge.com/TMDDFEPFU-U0405RJ3KC2-6b2f9b6354c3-512'
}, 
{
  id:'11',
  name: 'Washington Gama',
  turma: '24-A',
  types: ['Javascript', 'Typescript', 'JAVA', 'Python', 'Portugol'],
  alias: 'Cumpadi Wash',
  animal: 'Corvo',
  cidade: 'Feira de Santana - BA',
  frase: 'Ximboca',
  pic: 'https://ca.slack-edge.com/TMDDFEPFU-U03H9LED2BA-e762ff95c734-512'
},
{
  id:'12',
  name: 'Débora Marim',
  turma: '27-B',
  types: ['JS', 'MySQL', 'React', 'Redux'],
  alias: 'Debs',
  animal: 'Gato',
  cidade: 'Santa Bárbara-MG',
  frase: 'Feito é melhor que perfeito!',
  pic: 'https://ca.slack-edge.com/TMDDFEPFU-U0405NC490B-b5d317391482-512'
},
{
  id:'13',
  name: 'Camilla Skaff',
  turma: '27-B',
  types: ['JS', 'MySQL', 'React', 'Redux'],
  alias: 'Camilinha',
  animal: 'Coelho',
  cidade: 'São Paulo-SP',
  frase: 'Bora comer!',
  pic: 'https://ca.slack-edge.com/TMDDFEPFU-U03V58N61AB-1b0bff9d4d37-512'
},
]
